### ISSUE TITLE
REUSE_DB + TEST_NAME + Table Sync

### ISSUE THREAD

**Issue by rdegges** [django-nose/django-nose#106]
Hi all. I'm going to do the best I can to explain the issue I'm having, which I can verify is present in the master branch of django-nose, as well as the stable release.

What I'm trying to do is run my tests against a PostgreSQL database that already exists, and whose purpose is solely to run unit tests. EG: I've created a database on a remote host that is to be used exclusively for unit tests.

To this end, I've used Django's TEST_NAME key in the DATABASES dict, which allows me to override the default test database name to a name of my choosing.

So my configuration looks something like:

``` python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'blah', # production db name
        'USER': 'blah',
        'PASSWORD': 'blah',
        'HOST': 'blah',
        'PORT': 'blah', 
        'TEST_NAME': 'specialtestdbname',
    }
}}}}
````

What's happening, however, when I run `REUSE_DB=1 python manage.py test` (after hooking up the NoseTestSuiteRunner), is that django-nose does NOT create the tables in my database, 'specialtestdbname'. Instead, it tries to run the tests against the database without first creating the necessary tables.

What I'd like to see happen is:

- django-nose recognize that my database exists, and therefore not try to create it (this works right now).
- django-nose to create all my tables (it is not doing this)
- django-nose to run my tests
- django-nose to destroy all my tables (but not the database!)

Does that make sense? I think this would be pretty awesome.

Thank you.

**Comment by jwhitlock** [comment]
We have a lot of re-writing to do to catch up with the test infrastructure changes in Django.  In particular, the [settings](https://docs.djangoproject.com/en/1.8/ref/settings/#databases) have changed in 1.7, and there is now a [--keepdb flag](https://docs.djangoproject.com/en/1.8/topics/testing/overview/#the-test-database) to avoid deleting the test database.

I think it will be a while before the core developers have the bandwidth to add features like this, so I'm closing for now.

**Comment by rdegges** [comment]
Makes perfect sense ^^ Thanks for the response =)
