### ISSUE TITLE
Using south and coverage with django_nose results in models have incorrect coverage report.

### ISSUE THREAD

**Issue by ferrouswheel** [django-nose/django-nose#107]
Running django_nose using `--with-coverage`, and with south installed, results in incorrect coverage reporting. This is particularly a problem for model.py, but probably messes with declarative statements in other modules too.

This seems to be because south gets to do it's magic before plugins are run, so coverage isn't initialized:

```python
# Django < 1.2 compatibility
test_runner = settings.TEST_RUNNER
if test_runner.endswith('run_tests') or test_runner.endswith('run_gis_tests'):
    import warnings
    warnings.warn(
        'Use `django_nose.NoseTestSuiteRunner` instead of `%s`' % test_runner,
        DeprecationWarning)


TestRunner = get_runner(settings)
```

Not sure if this is just a limitation one has to deal with (I couldn't think of an obvious fix to submit as a patch), but I wanted to at least report it. I spent a fair while trying to work out why my models.py were reporting only 10% coverage and this'll hopefully be easy to search for.

As mentioned in other related coverage issues, the workaround is:

```
coverage run ./manage.py test
```

**Comment by foxwoods369** [comment]
I'm getting this as well right now in django 1.7.2. I'm not sure what's different about my setup (maybe django-configurations) that is causing this for me & not others. A hack to get coverage back to normal is to add is to add to the end of this function in the coverage plugin:
```python
    def begin(self):
        """
        Begin recording coverage information.
        """
        log.debug("Coverage begin")
        self.skipModules = sys.modules.keys()[:]
        if self.coverErase:
            log.debug("Clearing previously collected coverage statistics")
            self.coverInstance.combine()
            self.coverInstance.erase()
        self.coverInstance.exclude('#pragma[: ]+[nN][oO] [cC][oO][vV][eE][rR]')
        self.coverInstance.load()
        self.coverInstance.start()

        # Delete the modules from sys.modules hack
        for mod in sys.modules.keys():
            if mod.startswith(tuple(self.coverPackages)):
                del(sys.modules[mod])
```
After checking this works I'm going to locally create a new plugin that mimics the usual coverage plugin but overrides this bit. Of course, this is dependent upon having the packages specified, but a similar approach could probably be used if django-nose passed along the root directory.

Can anyone suggest a better workaround? Is this actually safe enough to do?

**Comment by jwhitlock** [comment]
Same issue as #180.  I'm closing this one to consolidate discussion on the new issue.
