### ISSUE TITLE
Mongoengine support

### ISSUE THREAD

**Issue by serpulga** [django-nose/django-nose#132]
Hi, 
I'm writing an application with django and mongoengine. When I try running tests I get: ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.Though I understand/expect this error, I wonder whether there is a way to set mongo as the django-nose database, or to not using a DB at all?.

**Comment by jwhitlock** [comment]
Same as #157.  Please pile on +1, PRs and suggestions over there.
