### ISSUE TITLE
`--noinput` not working?

### ISSUE THREAD

**Issue by moeffju** [django-nose/django-nose#135]
We’re using django-nose==1.2 within Jenkins and sometimes when tests fail, the test DB will not get deleted. All subsequent runs will then fail because there is no one at the terminal to enter “yes” or “no”. It seems like --noinput is not working. Should it? Is there a workaround?

**Comment by aamirtharaj-rpx** [comment]
I have the same issue I am using django-nose==1.3 and Django 1.7.7

**Comment by jwhitlock** [comment]
--noinput is working with current master, and if being used to delete existing test databases in the TravisCI database tests:

https://travis-ci.org/django-nose/django-nose
https://travis-ci.org/django-nose/django-nose/jobs/69352053 (py27-django-17-postgres, search for "Got an error creating the test database").

Can you retry with django-nose 1.4.1?

**Comment by jwhitlock** [comment]
No response from @moeffju or @aamirtharaj-rpx, assuming fixed in v1.4.1
