### ISSUE TITLE
How to provide nose parameters?

### ISSUE THREAD

**Issue by andresriancho** [django-nose/django-nose#168]
How do you pass nose parameters from the command line? In an early blog post from the original django-nose author I found a mention to `--`, which still seems to do something:
```console
$ python manage.py test -- -A smoke .
nosetests --verbosity 1 . -A smoke --with-yanc --with-id -s -v -- -A
...smoke tests are run...
```
But afterwards:
```text
80 Failure: OSError (No such file /home/pablo/pch/octopus/-A) ... ERROR

======================================================================
ERROR: Failure: OSError (No such file /home/pablo/pch/octopus/-A)
----------------------------------------------------------------------
```

So... how do I provide extra parameters to nose in order to choose my tests on run time?

**Comment by jwhitlock** [comment]
`./manage.py test --help` shows the options, which includes:

```
  -a ATTR, --attr ATTR  Run only tests that have attributes specified by ATTR
                        [NOSE_ATTR]
  -A EXPR, --eval-attr EXPR
                        Run only tests for whose attributes the Python
                        expression EXPR evaluates to True [NOSE_EVAL_ATTR]
```
`django-nose` merges nose and Django test options together, so I think the modern version of that example is:

```
$ python manage.py test -A smoke .
```
This gives me an error however.  It looks like the parameter "smoke" is not being passed through to nosetests, which looks like a bug.

**Comment by jwhitlock** [comment]
Opened #219 to cover the bug in Django 1.8.
