### ISSUE TITLE
builds broken for latest django (1.8)

### ISSUE THREAD

**Issue by conrado** [django-nose/django-nose#178]
The trunk builds are broken because of django/django@8568638

The option parser was changed to argparse, and an optparse compatability layer was introduced. I don't believe the hackety way of "option renaming" can be done as it is right now.

See:
https://github.com/django-nose/django-nose/blob/bfeb0983cce5d78c88a6099057a746c795574fa3/django_nose/runner.py#L102

**Comment by hwkns** [comment]
Here's more info from the Django 1.8 docs:
https://docs.djangoproject.com/en/1.8/howto/custom-management-commands/#custom-commands-options

And here's the stack trace I got when trying to run tests with `django-nose` on Django 1.8a1:
```
Traceback (most recent call last):
  File "/var/www/streisand/streisand/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/.venv/lib/python3.4/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/vagrant/.venv/lib/python3.4/site-packages/django/core/management/base.py", line 378, in run_from_argv
    parser = self.create_parser(argv[0], argv[1])
  File "/home/vagrant/.venv/lib/python3.4/site-packages/django/core/management/base.py", line 327, in create_parser
    parser.add_option(opt)
  File "/usr/lib/python3.4/optparse.py", line 1007, in add_option
    self._check_conflict(option)
  File "/usr/lib/python3.4/optparse.py", line 982, in _check_conflict
    option)
optparse.OptionConflictError: option -v/--verbose: conflicting option string(s): -v
```

**Comment by hwkns** [comment]
@jsocol Django 1.8 is in beta now, and one obvious step to help get it out the door with fewer bugs is to have users run their projects' test suites against it.  With this bug, that task is a lot more difficult.  Is there anything I can do to help?

**Comment by mrunge** [comment]
Yeah, I would love to see this fixed, as it prevents OpenStack Horizon from gating on newer Django releases.

**Comment by jthi3rry** [comment]
Not sure if it's the best way to fix it, but this works: https://github.com/django-nose/django-nose/pull/192

**Comment by hwkns** [comment]
@jsocol FYI, Django 1.8 now has a release candidate.

**Comment by nostalgiaz** [comment]
+1

**Comment by brandonjschwartz** [comment]
+1

**Comment by DebauchedSloth** [comment]
+1.

1.8 now released.

**Comment by limnick** [comment]
+1

**Comment by gigaroby** [comment]
+1

**Comment by Juleship** [comment]
+1

**Comment by illagrenan** [comment]
+1

**Comment by fpruitt** [comment]
:+1:

**Comment by imkevinxu** [comment]
+1

**Comment by brandonjschwartz** [comment]
@imkevinxu thanks for your work on this! :)

**Comment by conrado** [comment]
It's the same hack @jthi3rry had made. mind you, it's all pretty hacky here anyway...

**Comment by imkevinxu** [comment]
@conrado yeah I just copied @jthi3rry 's code into my own repo... but then I ran into the same unicode/int operation TypeError as noted by https://github.com/django-nose/django-nose/pull/192#issuecomment-88183127 so the hack doesn't work anyway...

**Comment by kevinglover** [comment]
+1

**Comment by glynjackson** [comment]
+1

**Comment by josemariaruiz** [comment]
+1

**Comment by alexph** [comment]
+1

**Comment by demeee** [comment]
+1

**Comment by rickwebb** [comment]
+1

**Comment by rafaelcaricio** [comment]
+1

**Comment by MackJay** [comment]
+1 Updates on this? All my CI tests have stopped working! ``ImportError: No module named creation`` and ``optparse.OptionConflictError: option -v/--verbose: conflicting option string(s): -v``

**Comment by rafaelcaricio** [comment]
@MackJay I have the same issue.

**Comment by ALAINAbbe** [comment]
Django nose is just a test runner, so I assume you can ditch it and just use nose outright? 

Django 1.8 has been out for like 12 days+ with a good Beta period too! I know this is a free tool, one which I appreciate. I'm personally using Django 1.8 for the new PostgreSQL and UUIDField functionality but, with my CI broken I'm not allowed to push the Django 1.8 changes.

**Comment by jwhitlock** [comment]
@ALAINAbbe, django-nose also loads Django settings, so using nose directly isn't feasible.

Here are some strategies for dealing with packages with slow releases.

You can use the older Django version until all your dependencies are updated.  This line in your requirements would keep you on Django 1.7:

    # Django 1.8 is waiting on django-nose
    Django>=1.7,<1.8

You can install from a pull request that fixes your issue.  Here's the requirements.txt segment:

    # Until django-nose>1.3 is released
    git+git://github.com/jwhitlock/django-nose@178_fix_argparse_v2#egg=django-nose

You can fork the project, create a branch, and apply patches until you have something that works for you:

    # django-nose 1.3 doesn't work w/ Django 1.8
    git+git://github.com/myuser/django-nose@my_branch#egg=django-nose

You can remove the dependency.  The Django team is aggressively adding features that used to require third-party packages, so working with the included batteries is a better option with each release.  For django-nose, you just comment out the test runner to get the default [DiscoverRunner](https://docs.djangoproject.com/en/1.8/topics/testing/advanced/#defining-a-test-runner) 

```python
# TEST_RUNNER = 'django_nose.NoseTestSuiteRunner'
```

**Comment by imkevinxu** [comment]
This seems to be the a pull request that fixes everything for 1.8 https://github.com/django-nose/django-nose/pull/196

Who's in charge of merging?

**Comment by mrunge** [comment]
before mentioned pull request fixes my issues here. Thank you for pointing that out and for requesting a merge.

**Comment by glynjackson** [comment]
me too +1 on getting this merged ;)

**Comment by boRk3D** [comment]
+1

**Comment by LennyLip** [comment]
+1

**Comment by ezarowny** [comment]
:+1:

**Comment by yannik-ammann** [comment]
+1
any information about a release with django 1.8 support?

**Comment by conrado** [comment]
Apparently there is a fix, linked here somewhere. Why don't you fork it and
use it? That way you also test it

**Comment by patroqueeet** [comment]
+1 for seing this into the stable release

**Comment by JohnTke** [comment]
Who is responsible for merging on django-nose? Can anyone give us updates on what we are waiting for? :+1: on getting this into release please.

**Comment by ALAINAbbe** [comment]
18 open pull requests to-date, seems like a lot of people are contributing but no one is listening, please, please moderators we want this into a stable release! This has been open since Oct 21, 2014, you have fixes ready. I know there are workarounds but who wants that. Like a lot of comments here builds are broken +1 a millions times!

**Comment by JohnTke** [comment]
@ALAINAbbe my sentiments exactly, so thankful this project exists but really struggling to like it right now. I'm being told how we have to move to Django 1.8 meanwhile one of the most important parts, testing does not work. Sad Face - Love you all, don't shoot me!

**Comment by glynjackson** [comment]
+1 for seing this into the stable release

**Comment by rickwebb** [comment]
+1

**Comment by demeee** [comment]
+1

**Comment by Ironside74** [comment]
+1

**Comment by conrado** [comment]
A maintainer has been added to the repository, and he has said a version bump is on the way, so before we do do that, he has asked for opinion on other pull requests that are relevant and should be included in django-nose 1.4.

If you have tested a PR you would like to see included in 1.4, you could mention it in #196, and we can work to rebase and include them into the release.

**Comment by jwhitlock** [comment]
I've added issue #202 to collaborate on today's release.  I'm guessing there will be a 1.4.1 soon after :)

**Comment by glynjackson** [comment]
@conrado So cool, #196 'seems' works for me.

**Comment by syrusakbary** [comment]
+1
