### ISSUE TITLE
Needs update to work with Django 1.8

### ISSUE THREAD

**Issue by vkurup** [django-nose/django-nose#182]
As of a few days ago, line 23 of runner.py fails with the master branch of Django, due to django/django#3899

```
    from django.db.backends.creation import BaseDatabaseCreation
```
needs to change to:
```
    from django.db.backends.base.creation import BaseDatabaseCreation
```

**Comment by hwkns** [comment]
Fixed in https://github.com/django-nose/django-nose/commit/ae2c1bbe851131adbec773fe1bebbd03d9be2bd2
