### ISSUE TITLE
Release 1.4

### ISSUE THREAD

**Issue by jwhitlock** [django-nose/django-nose#202]
A 1.4 release is needed for Django 1.8 compatibility.

Includes PRs
* #185 - Django 1.8 compatibility
* #188 - Add contribute.json
* #187 - Support --testrunner
* #194 - Add 1.8 to test matrix
* #196 - Convert nose optparse options to argparse 

Any other PRs that should be included?

**Comment by glynjackson** [comment]
Could we see pull request https://github.com/django-nose/django-nose/pull/145 included in this release :)

**Comment by erikrose** [comment]
@jwhitlock Do you need PyPI privs? What's your username?

**Comment by jwhitlock** [comment]
@erikrose I would have figured that out in a few hours :)  I'm John.Whitlock on PyPi.

**Comment by jwhitlock** [comment]
OK, ready to release once I'm added to PyPi

**Comment by erikrose** [comment]
Have at it!

**Comment by imkevinxu** [comment]
I'm so excited!

![](https://a248.e.akamai.net/f/248/6650/10/rack.1.mshcdn.com/media/ZgkyMDEzLzA3LzA1LzBhL2V4Y2l0ZWRiYWJ5LjlhZWY3LmdpZgpwCXRodW1iCTEyMDB4OTYwMD4/f01f5d34/cc5/excited-baby.gif)

**Comment by ezarowny** [comment]
I'm also very excited!

![Yay Food!](http://3.bp.blogspot.com/-8T7jNkDGmmg/UcCrXfyZNOI/AAAAAAAAMlg/7I0aO-N-r-Q/s1600/excited-corgi.gif)

**Comment by jwhitlock** [comment]
Released: https://pypi.python.org/pypi/django-nose/1.4

**Comment by rafaelcaricio** [comment]
:heart:

**Comment by jsocol** [comment]
![](http://i.imgur.com/vkbOQLL.gif)

Thanks for jumping in @jwhitlock!

**Comment by jwhitlock** [comment]
1.4.1 coming: #203

**Comment by glynjackson** [comment]
much love! thank you, thank you!!!!!

o and...
![baby ninja](https://cloud.githubusercontent.com/assets/426906/7318943/d7955d7c-ea88-11e4-8caa-30793be62940.gif)

**Comment by gepoch** [comment]
:+1: Thank you so much!
