### ISSUE TITLE
Django upgrade to 1.8 issue - Argparse option callback is not supported

### ISSUE THREAD

**Issue by poojasgada** [django-nose/django-nose#223]
I have been trying to move to django 1.8 and currently stuck with this issue:

lib/python2.7/site-packages/django_nose/runner.py", line 247, in add_arguments
(attr, value))
AssertionError: argparse option callback=<function _log at 0x114fd1c80> is not supported

Looked around, could not find a solution. Can someone point me in the right direction ?

I hit this issue when i try to run:

python manage.py test

django-nose version - 1.4.1
django version 1.8.3

Any help will be kindly appreciated.

**Comment by jwhitlock** [comment]
Django 1.8 [switched from optparse to argparse](https://docs.djangoproject.com/en/1.8/releases/1.8/#custom-test-management-command-arguments-through-test-runner), however nose [continues to use optparse](https://github.com/nose-devs/nose/issues/898).  django-nose 1.4 adds a translation layer from Django argparse options to nose's opt parse options.  None of the default plugins use the callback option, so it was left untranslated.

Which plugin includes a ``callback=`` option?  Run ``nosetests --plugins`` to get a list of available plugins.  Here's mine:
```
$ nosetests --plugins
Plugin capture
Plugin failuredetail
Plugin xunit
Plugin deprecated
Plugin skip
Plugin multiprocess
Plugin logcapture
Plugin coverage
Plugin attributeselector
Plugin doctest
Plugin profile
Plugin id
Plugin allmodules
Plugin collect-only
Plugin isolation
Plugin ipdb
Plugin pdb
```
I'm not sure how to see what plugins you are using - that may be set at the command line or a [nose config file](http://nose.readthedocs.org/en/latest/usage.html)

**Comment by poojasgada** [comment]
Here's my list:

$ nosetests --plugins
Plugin capture
Plugin failuredetail
Plugin xunit
Plugin deprecated
Plugin skip
Plugin multiprocess
Plugin logcapture
Plugin coverage
Plugin sqlalchemy
Plugin attributeselector
Plugin doctest
Plugin profile
Plugin id
Plugin allmodules
Plugin collect-only
Plugin isolation
Plugin pdb

I did a 
```
print(attr, option, value)
```
 in the part of the code where its trying to Convert optparse attributes to argparse attributes. 

``` 
callback --log-info <function _log at 0x110af2ed8>
```

It looks like it failing for these above values.

**Comment by jwhitlock** [comment]
It doesn't appear to be a plugin - you have the default list as well.  This must be from some other code, either in your project or from a dependency.  I don't think there is a way to determine the source from the ``add_arguments`` call.

You could try skipping the assertion, and seeing what the result is.  Change the code to something like:

```python
                    # Translating callbacks is not supported
                    if attr in cls._argparse_fail_if_not_none:
                         # assert value is None, (
                         #  'argparse option %s=%s is not supported' %
                         #   (attr, value))
                         continue  # Skip argument
```

**Comment by poojasgada** [comment]
Commented the lines as you mentioned. 

I think this was expected: 
```
/lib/python2.7/site-packages/django_nose/runner.py", line 261, in add_arguments
    parser.add_argument(opt_long, **option_attrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1280, in add_argument
    raise ValueError('unknown action "%s"' % (action_class,))
ValueError: unknown action "callback"
```
I appreciate your quick response for the issue. Thank you again.

**Comment by jwhitlock** [comment]
I'm sorry, this won't be an effective way to write this work around.  I'll either need to know the source of this option, so that I can reproduce locally, or you'll have to adjust the code until the issue goes away.

**Comment by poojasgada** [comment]
Thank you for all the help. For now, i have downgraded to 1.7.9. May need to revisit this when i eventually move to 1.8.x.

**Comment by jwhitlock** [comment]
I've been looking into command line parsing some more, and currently the Django command line parsing is thrown out before it gets to nose.  It may be safe to remove the ``cls._argparse_fail_if_not_none`` checks.  I'm still looking for a way to reproduce this issue, rather than blindly making changes.
