### ISSUE TITLE
Not outputting logs even with --nologcapture and -s

### ISSUE THREAD

**Issue by mikob** [django-nose/django-nose#224]
I'm getting no log output at all, only print statements show up correctly. Seems like it should be something simple... The logging handlers are setup correctly, as they work fine when I run the modules in standalone mode, for example.
```
django-nose==1.4.1
nose==1.3.7
nose-progressive==1.5.1
```

`./manage.py test ../scheduler --nologcapture -s -v 3`

I put an `ipdb.set_trace()` statement where a logger should be active:

```
ipdb> logger.level
0
ipdb> logger.disabled
False
ipdb> logger.handlers
[]
```

When I run the script in standalone mode, the logging outputs just fine and the logger looks like this at the same breakpoint:
```
ipdb> logger.level
20
ipdb> logger.disabled
False
ipdb> logger.handlers
[<django.utils.log.AdminEmailHandler object at 0x7ffa9ca88ba8>, <logging.handlers.RotatingFileHandler object at 0x7ffa9ca882b0>, <logging.StreamHandler object at 0x7ffa9d7dd3c8>]
```

**Comment by jwhitlock** [comment]
I don't see any code in django-nose that manipulates logging.  Try running without nose-progressive.  It has a ``--logging-clear-handlers`` that might be getting engaged (either a bug or a nose configuration file).

**Comment by mikob** [comment]
Hmm. I suppose the issue must be with nose itself. I tried uninstalling nose-progressive and reinstalling django-nose along with nose to no avail, FYI. Closing this and bringing it up with the nose project.
