### ISSUE TITLE
Jasmine-style "focused" test running

### ISSUE THREAD

**Issue by evenicoulddoit** [django-nose/django-nose#238]
I've been using [Jasmine](http://jasmine.github.io/) recently, and I've found it does a tonne of things really nicely. One of those is the ability to run ["focussed tests"](http://jasmine.github.io/2.1/focused_specs.html) where only a single test or a subset of tests actually run. This works really nice when debugging an individual test as you don't need to plow through the entire suite to just get the resolution of one.

Clearly we can already do this sort of thing with Django-nose but calling an individual TestCase or test from the command line, but this takes time. For example

`python manage.py test app.tests.test_something:FooTestCase.test_bar_works`

is quite a hassle to write, and it's my opinion that a simpler option would be far more useful. I'm not sure how this would apply to Python, perhaps through the use of a decorator `@focused` which would add the method or test case to a register of white-listed tests to run.

I'd be happy to take a look at this at some point if it piques anyone's interest.

**Comment by jwhitlock** [comment]
Please try [nose's Attrib plugin](http://nose.readthedocs.org/en/latest/plugins/attrib.html).

**Comment by evenicoulddoit** [comment]
Thanks for the pointer, seems pretty reasonable :)

**Comment by jwhitlock** [comment]
Now that #142 is fixed, I'm closing this request in favor of using the attrib plugin.  Here's a sample usage:

```
from django.test import TestCase
from nose.plugins.attrib import attr

class MyTestCase(TestCase):
    @attr("focused")
    def test_focus_one(self):
        """My focused test"""
        ...

    @attr("focused")
    def test_focus_two(self):
        """Another focused test"""
        ...

    def test_unfocused(self):
        """An unfocused test"""
        ...
    
```

Running just the focused tests: ``./manage.py test --attr focused``

See the docs for [nose's Attrib plugin](http://nose.readthedocs.org/en/latest/plugins/attrib.html) for more options.
