### ISSUE TITLE
Listing django in install_requires can cause upgrades to upgrade Django

### ISSUE THREAD

**Issue by jsocol** [django-nose/django-nose#239]
With Django 1.7.10 installed, I ran:

```bash
pip install -U django-nose
```

and it also updated Django to 1.8.5 because it's in `install_requires` in `setup.py`. This seems logical, but can have serious unintended consequences, which is why I usually avoid listing Django itself as an actual install dependency.

**Comment by jgoettsch** [comment]
If this is a bug then the bug is in pip.

If you require a specific version of a package you should be pinning it with [pip-tools](https://github.com/nvie/pip-tools/) or in a requirements.txt file.

**Comment by jsocol** [comment]
@jgoettsch It's not a "bug" so much as "documented, correct behavior that may not be doing the right job". See https://github.com/pypa/pip/pull/3194

**Comment by jsocol** [comment]
> If you require a specific version of a package you should be pinning it with pip-tools or in a requirements.txt file.

The issue is that if you type `pip install -U django-nose` to get the latest version of django-nose, instead of 1) finding the latest version, 2) editing your requirements.txt, 3) `pip install -Ur requirements.txt`, you'll get the latest Django, too.

This isn't an uncommon workflow. `pip install -U django-nose` is a _lot_ faster than checking all requirements, and is reasonable if you want to say "I'm going to try updating this lib in the project, so get whatever's latest and if it works I'll update requirements.txt."

**Comment by jgoettsch** [comment]
Yes... if you tell pip to upgrade your packages it will upgrade your packages.

I agree this is a problem for a lot of users of a lot of different packages because certain dependencies (like Django) cannot be updated so easily. But the solution is not for packages to stop listing their dependencies in their setup file. This would mean you'd have to update everything by hand and would be... chaotic.

[pip-tools](https://github.com/nvie/pip-tools/) solves the problem.

**Comment by jsocol** [comment]
OK, so this isn't a conversation worth having. I'll let more active django-nose maintainers than me decide if it's worth changing this as a practical solution—until `pip` supports a more full-featured one. Dependency management is hard, and frameworks are sort of special, _a priori_, as dependencies go.

**Comment by jwhitlock** [comment]
@jgoettsch yes, best practice is to pin the version in requirements.txt.  Soon, pip will support cryptographic hashes of packages, and I expect best practices in 2016 to be 1) include the hashes, and 2) include all dependencies of your package as well.

I have a similar workflow to @jsocol's when updating packages, but I try to keep up with the latest everything, so it looks more like:

```
cat requirements.txt | cut -d= -f1 | xargs -n1 pip install -U
```

I can see how this would be super annoying if you were forced to stay on an old version of Django.

I think dropping Django from the install requirements has very few downsides, and it's on the roadmap for the next version.  It's also not my itch, so I'm hoping that someone will submit a PR.

**Comment by jsocol** [comment]
See #248
