### ISSUE TITLE
RuntimeError on Django 1.9

### ISSUE THREAD

**Issue by sean2000** [django-nose/django-nose#249]
Happens when running tests on CircleCI
````
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/nose/loader.py", line 523, in makeTest
    return self._makeTest(obj, parent)
  File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/nose/loader.py", line 568, in _makeTest
    obj = transplant_class(obj, parent.__name__)
  File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/nose/util.py", line 642, in transplant_class
    class C(cls):
  File "/home/ubuntu/virtualenvs/venv-2.7.10/lib/python2.7/site-packages/django/db/models/base.py", line 103, in __new__
    "application was loaded. " % (module, name))
RuntimeError: Model class nose.util.C doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. 
````

CircleCI environment:

Django 1.9
django-nose 1.4.2
nose 1.2.1

**Comment by jwhitlock** [comment]
Is ``django-nose`` in the ``INSTALLED_APPS``?  See [docs](https://django-nose.readthedocs.org/en/latest/installation.html) for details.

**Comment by sean2000** [comment]
Yes it is

**Comment by jwhitlock** [comment]
I don't see this in my Django 1.9 test runs. Is this a public project? I might be able to see something causing it.

My current guess is that nose is detecting a model class that it thinks it should run tests - maybe because it is named Test, or TestFoo, or FooTest, and it wrapping it in transplant_class, which is freaking out Django's model loader.  If this is the case, it may work if you rename the class, or don't do Python path manipulations, or add a ``__test__= False`` class declaration.

**Comment by sean2000** [comment]
Its a private project. The tests are passing fine with the same code on Django 1.8.7 so i'm not sure what model classes could be causing the problems.

**Comment by sean2000** [comment]
I just went back and read the release notes for Django 1.9. ``All models need to be defined inside an installed application or declare an explicit app_label``
That explains why it would work in 1.8.7 and fail in 1.9

**Comment by sean2000** [comment]
OK I git it working. I had a model called ``Testimonial`` that was causing the problem, I set ``__test__=False`` on it and now the tests pass. Thanks for the help!

**Comment by jwhitlock** [comment]
Thanks for the info - I didn't think ``Testimonial`` would match, but I guess it does. I'll have to avoid this as a model name, along with ``Testosterone`` and ``Testicles``.
