### ISSUE TITLE
Without an explanation REUSE_DB=(empty) means True

### ISSUE THREAD

**Issue by wdoekes** [django-nose/django-nose#250]
In 1f682466bdc94f5dd06c6c9ee5610328f15f67c1, the REUSE_DB check was changed from `('0', 'false', '')` to mean `False`, to `('1', 'true', '')` meaning `True`.

Unless there is very good reason, having an empty environment variable mean True, while unset means False, is counter-intuitive.

Is there a very good reason?

**Comment by jwhitlock** [comment]
Is there a bug, or are you complaining about a decision made 3 years ago?

**Comment by wdoekes** [comment]
In 2012, we had the following situation:

* (no-env): REUSE
* `FORCE_DB=`: REUSE
* `FORCE_DB=0`: REUSE
* `FORCE_DB=1`: no-reuse

That was changed to this:

* (no-env): no-reuse
* `REUSE_DB=`: REUSE <-- this is a bug
* `REUSE_DB=0`: no-reuse
* `REUSE_DB=1`: REUSE

I'm not complaining about the switch from FORCE_DB to REUSE_DB. That makes all the sense in the world, I'm complaining about the 2nd item in the second list ("this is a bug").

(no-env) should generally mean the same as `ENV=(empty)` unless you have a good reason. I don't see any good reason. So yes, I'd call it a bug.
