### ISSUE TITLE
Docs differ from README as to which versions of django are supported

### ISSUE THREAD

**Issue by djg321** [django-nose/django-nose#262]
The README says that only versions `1.8` and `1.9` are supported while the [docs linked to from the README](https://django-nose.readthedocs.org) also include `1.4` and `1.7`.

**Comment by jwhitlock** [comment]
I plan to drop support for old releases of Django that aren't supported by Django in the next version.  This will require work, for example dropping the South migrations.  Users of old versions can upgrade to 1.0.0, upgrade to a Django 1.8, and the upgrade to latest releases.

**Comment by jwhitlock** [comment]
https://github.com/django-nose/django-nose/releases/tag/v1.4.4 dropped support for South, and has accurate Django support notes.
