### ISSUE TITLE
Cannot specify a test name

### ISSUE THREAD

**Issue by d33tah** [django-nose/django-nose#265]
Consider the following tests.py:

```
from django.contrib.staticfiles.testing import StaticLiveServerTestCase

class AdminTestCase(StaticLiveServerTestCase):

    def test_example(self):

        import sys
        sys.stderr.write("Hello, world\n")
```

When I run `./manage.py test projectname`, the test runs. When I run `./manage.py test projectname.tests.AdminTestCase.test_example`, I get "Ran 0 tests". Why is that?

**Comment by jwhitlock** [comment]
The syntax for [selecting tests](http://nose.readthedocs.io/en/latest/usage.html#selecting-tests) is:

```
./manage.py test projectname.tests:AdminTestCase.test_example
```

**Comment by d33tah** [comment]
@jwhitlock: you're right! That fixed it. Sorry for the trouble.
