### ISSUE TITLE
--tag option provided in help but not implemented

### ISSUE THREAD

**Issue by makyo** [django-nose/django-nose#277]
I've tagged some tests to ensure that views take into account group membership or lack thereof, but can't get the test command to recognize the `--tag` option for nose or as specified in [the Django docs](https://docs.djangoproject.com/en/1.10/topics/testing/tools/#tagging-tests).

django-nose==1.4.4
Django==1.10.2
nose==1.3.7

```
$ python manage.py test --tag="as_user" administration.tests
nosetests administration.tests --tag=as_user --verbosity=1
Usage: manage.py [options]

manage.py: error: no such option: --tag
```

**Comment by makyo** [comment]
Pardon me, not actually a nose option.  Went by `manage.py test --help`:

```
...
  --tag TAGS            Run only tests with the specified tag. Can be used
                        multiple times.
  --exclude-tag EXCLUDE_TAGS
                        Do not run tests with the specified tag. Can be used
                        multiple times.
...
```

**Comment by jwhitlock** [comment]
Handling Django test options requires hard-coding them.  See [runner.py](https://github.com/django-nose/django-nose/blob/master/django_nose/runner.py#L85-L92).  The new 1.10 options haven't been added yet.

**Comment by Songyu-Wang** [comment]
@jwhitlock 
@makyo 
randomly found this issue
Seems like this issue is fixed. 
You should close this issue

**Comment by jwhitlock** [comment]
Thanks @Songyu-Wang

**Comment by kutenai** [comment]
Is this still an issue with Django 2.2 and beyond? I've spent about an hour trying to figure out what "I" am doing wrong... and maybe nothing.

**Comment by jwhitlock** [comment]
``--tag`` is in the exclusion list in the current code:

https://github.com/django-nose/django-nose/blob/42eae06b60f7f91e91473e49e6f295221339c3ba/django_nose/runner.py#L93

It may help to open a new issue, and include your versions, the failing command, and the output.

**Comment by brianpeiris** [comment]
If you've found this issue because you want to use tags to filter your test runs, you should be able to use nose's `-a` flag with the `@attr()` decorator, via nose's built-in plugin: https://nose.readthedocs.io/en/latest/plugins/attrib.html
