### ISSUE TITLE
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

### ISSUE THREAD

**Issue by ManojDatt** [django-nose/django-nose#280]
django-nose while runing on django-1.10
$ nosetests app_directory/../tests.py --with-html

I am getting django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
error every time.

**Comment by jwhitlock** [comment]
``nosetests`` does not know how to call the Django app registry setup.  Try this:

```
./manage.py test app_directory/../tests.py --with-html
```

See [the usage docs](https://django-nose.readthedocs.io/en/latest/usage.html) for more.
