### ISSUE TITLE
Supporting standalone test runner

### ISSUE THREAD

**Issue by dcramer** [django-nose/django-nose#46]
This is more of a draft idea, and I'm not entirely sure how we should approach it, but it'd be nice if we could somehow support a standalone test runner a bit easier.

Right now I end up with something containing, at minimum, the following::

    #!/usr/bin/env python
    import sys
    import os, os.path
    from optparse import OptionParser

    from django.conf import settings

    parent = os.path.dirname(os.path.abspath(__file__))
    sys.path.insert(0, parent)

    if 'DJANGO_SETTINGS_MODULE' not in os.environ:
        os.environ['DJANGO_SETTINGS_MODULE'] = 'disqus.conf.settings.test'

    from django_nose import NoseTestSuiteRunner

    def runtests(*test_args, **kwargs):
        if 'south' in settings.INSTALLED_APPS:
            from south.management.commands import patch_for_test_db_setup
            patch_for_test_db_setup()

        test_runner = NoseTestSuiteRunner(**kwargs)

        failures = test_runner.run_tests(test_args)
        sys.exit(failures)

    if __name__ == '__main__':
        parser = OptionParser()
        parser.add_option('--verbosity', dest='verbosity', action='store', default=1, type=int)
        parser.add_options(NoseTestSuiteRunner.options)
        (options, args) = parser.parse_args()

        if not args:
            args = ['tests', 'disqus']

        runtests(*args, **options.__dict__)

**Comment by jwhitlock** [comment]
Closing as a distraction, same as #140.  https://github.com/nosedjango/nosedjango seems like a good alternate, still maintained as of Feb 2015.
