### ISSUE TITLE
Method definitions as missing

### ISSUE THREAD

**Issue by islavov** [django-nose/django-nose#53]
Might be a problem on my side, but when I run some tests like this:
python manage.py test project.utils --with-coverage --cover-package=project.utils.cache_util

I get

Name                     Stmts   Miss  Cover   Missing
------------------------------------------------------
project.utils.cache_util      61     16    74%   1-11, 32, 40, 45, 52, 56, 64, 75, 78, 81, 84, 93

All those missing are either imports or class definitions or class methods.

Any ideas?

**Comment by jwhitlock** [comment]
In general, if a module gets imported before coverage is loaded, the module will show up as missing.  Django 1.7 exposes more people to this issue, because app loading also loads modules.  Closing this bug in favor of more general problem in #180.
