### ISSUE TITLE
Dirty DB

### ISSUE THREAD

**Issue by zvictor** [django-nose/django-nose#89]
I am having `IntegrityError` problems when `REUSE_DB` is activated.
It happens because my tests try to **recreate instances** already existent in database, **created on earlier runs**.

```ruby
IntegrityError: duplicate key value violates unique constraint "auth_user_username_key"
```

I believe that **every time** we run our tests, it **should found the same** enviroment.
Repeting tests, must repeat results.
Nowadays, it is not what is happening, because it **is accumulating dirt** on database.

So, I propose we do a **rollback** after tests run. Not after each test, as proposed on #20 (would be very slower, and can be done overiding TestCase), but **after all tests are done**.

I am new with `nose` and `django-nose`, so I appreciate to know your ideas.

**Comment by jwhitlock** [comment]
There's enough broken in REUSE_DB=1 that I don't see us getting to this feature in the next 3 years either.  PRs with tests are welcome, but probably won't be merged until the rest of the REUSE_DB issues are fixed.
